### ISSUE TITLE
[Bug]: RTL Design issue

### ISSUE THREAD

**Issue by Saifallak** [andrewdwallo/filament-selectify#10]
### What happened?

![image](https://github.com/andrewdwallo/filament-selectify/assets/6053156/d56239e7-cc44-4bc3-a4e9-0eb96f44905c)

### How to reproduce the bug

just use RTL Language.

### Package Version

v2.0.5

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Windows, Linux

**Comment by Saifallak** [comment]
Example:

```php
 ToggleButton::make('is_active')
                        ->offColor('danger')
                        ->onColor('primary')
                        ->offLabel(__('No'))
                        ->onLabel(__('Yes'))
                        ->default(true)
                        ->columnSpan(1),
```

**Comment by andrewdwallo** [comment]
Okay will fix soon.

**Comment by andrewdwallo** [comment]
@Saifallak Fixed in latest release. 
https://github.com/andrewdwallo/filament-selectify/releases/tag/v2.0.6

**Comment by Saifallak** [comment]
That was quick, you're amazing ❤️
