### ISSUE TITLE
[FEATURE] Multi select

### ISSUE THREAD

**Issue by andreazanini** [andrewdwallo/filament-selectify#12]
### What happened?

I would like to have multiselect like the default Filament Select, but at the moment is not supported.
Since i'm registering trough a relation this would be really helpful.

now I use this
Select::make('categories')->multiple()->relationship(titleAttribute: 'name')->preload(),   

this should become
ButtonGroup::make('categories')->options(Category::all()->pluck('name','id'))->onColor('primary')->offColor('gray')->multiple()

### How to reproduce the bug

Feature request

### Package Version

3.0.0

### PHP Version

8.1.21

### Laravel Version

10.40.0

**Comment by andrewdwallo** [comment]
Please move this into a Discussion as this is not a bug. You can now make a Feature Request [here](https://github.com/andrewdwallo/filament-selectify/discussions/new?category=feature-requests).
