### ISSUE TITLE
[Bug]: UI bug in mobile version

### ISSUE THREAD

**Issue by bekbolot1407** [andrewdwallo/filament-selectify#15]
### What happened?

Hi, I have a problem with displaying buttons in the mobile version

**Here's my button form**
<img width="680" alt="Снимок экрана 2024-02-20 в 15 19 44" src="https://github.com/andrewdwallo/filament-selectify/assets/120478101/0abfb4bf-3efd-4f96-afcb-31a837a7879d">

**This is how I further invoke and display this button form on the page:**
<img width="960" alt="Снимок экрана 2024-02-20 в 15 20 10" src="https://github.com/andrewdwallo/filament-selectify/assets/120478101/5470f50f-98d4-4eb3-993b-3ea8041be334">

**The desktop version is fine:** 
<img width="1366" alt="Снимок экрана 2024-02-20 в 15 20 26" src="https://github.com/andrewdwallo/filament-selectify/assets/120478101/c1f36677-4529-47fd-8a40-736471bf6f3a">

**But on the mobile version, it's messed up**
<img width="542" alt="Снимок экрана 2024-02-20 в 15 20 38" src="https://github.com/andrewdwallo/filament-selectify/assets/120478101/cebe273e-ea28-47c3-94b5-c1a1b381d490">

**I can deliver ->gridDirection('row'), but it doesn't suit me**

### How to reproduce the bug

1. Create a livewire component
2. Create a form group of buttons
2. Call the form method in HTML markup

### Package Version

2.0

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

macOS, Windows, Linux

**Comment by andrewdwallo** [comment]
Okay well what do you want it to do in mobile? Do you want it to wrap?

**Comment by bekbolot1407** [comment]
I think it would be more correct to make it adaptive to the mobile version, to divide it into rows, columns. 
That is, there are static row and column by default. Now you can use only one of these options. 

And you can make it so that two variants are used at the same time. When the display is wide, then use column, and when it is narrow as in the mobile version, then use row and all this would happen automatically.

**Comment by andrewdwallo** [comment]
@bekbolot1407 Should be fixed now.
