### ISSUE TITLE
[Bug]: grid direction does not work in a fieldset component

### ISSUE THREAD

**Issue by saadj55** [andrewdwallo/filament-selectify#19]
### What happened?

I am trying to get he layout in a horizontal manner but the provided `gridDirection()` method does not work for me. I tried with `gridDirection('row')` but it didn't render its as a row of radio buttons. What could be the reason?

### How to reproduce the bug

try to render the component with `gridDirection('row')` in a fieldset component

### Package Version

2.0

### PHP Version

8.3.3

### Laravel Version

10.0

### Which operating systems does with happen with?

Windows

**Comment by saadj55** [comment]
Upon further tesitng, it doesn't work even outside of a fieldset.

**Comment by andrewdwallo** [comment]
Can you send me a picture of it?

**Comment by ronfuller** [comment]
@saadj55 I had the same problem, if you have a custom theme, you can fix with the following:

.selectify-button-group-grid {
    @apply md:grid-cols-2 !important;
}

@andrewdwallo 
I believe line 18 in button-group-blade needs to have "md:grid-cols-2" in order for the row direction to work correctly

**Comment by andrewdwallo** [comment]
Fixed by #21
